### PR TITLE
Address: can copy address to clipboard

### LINKED ISSUE #86: Update Address component to display shortened address
### Description

Would be handy to be able to display a shortened version of the address as well as having a one click copy to clipboard functionality on it.

### Why is this needed?

Wallet addresses are far too long and in most cases we don't need to display it in full in our dapp.

Showing the first 4 and last 4 chars is usually enough to get a glimpse of which address we're using.

We usually do things with an address, like copy and paste it into etherscan to check some transactions, paste it into opensea to see the account's NFTs etc... Since we're only showing the first/last 4 chars we need a way to copy to clipboard easily.

### Proposed Solution or API

This ticket includes 2 changes really:
- New prop on `Address` called `shortened` (bool) to display 4 first/last chars of an address
- Copy full address to clipboard onClick

Good to haves would be:
- Visual hint to show that the full address can be copied
- Visual feedback when address has been successfully copied to clipboard

### Additional Information

Let's start with the basic requirements and can work on the good to haves if we have time.

Make sure to create a new ticket with good to haves (as I think they are valuable) if we can't do this as part of this issue for some reason.

### PR DESCRIPTION
**Pull request by maximebonhomme**
Let's wait for PR#95 to be merged first and I'll fix any conflicts

Closes #86 

## Description

This PR includes changes to make the Address component copiable to clipboard. We're now able to provide a prop `<Address value='0x000' copiable />` to enable users to copy the address to their clipboard.

## What changed

- New prop on `Address` called `copiable` as type `boolean` - default is falsy
- When `copiable` is set to `true` we're now displaying a Copy Icon on the far right of the input - This allows users to know they can copy the address to their clipboard
- When users successfully copied the address to their clipboard we're replacing the Copy Icon by a Check Icon as a success feedback
- Added error state to notify users if copy to clipboard has failed

## 📝 Additional Information

I have added `@chakra-ui/icons` package to add icons, thinking that's the most suitable for us atm as we're already using chakraUI - any concerns let me know

## Screenshot

copiable set to true:
copiable set to true

copied successfully:
copied

### CODE REVIEW

**Comment by maximebonhomme** [comment]
chromataic failing with `Error: ✖ Missing project token` not sure if I need to add anything to my repo/branch?

**Comment by christiananese** [comment]
> chromatic failing with `Error: ✖ Missing project token` not sure if I need to add anything to my repo/branch?

You need to clone the original repository and create a PR from there. I think @etr2460 updated the README. It's an issue with Chromatic, it's not possible to deploy from forked repositories.

**Comment by maximebonhomme** [comment]
ah I tried that and didn't have permission to push to the repo hence why I foked it @christiananese 
anyway I could be given push permission if that's the case @etr2460 ?

**Comment by Dhaiwat10** [comment]
@maximebonhomme gave you write access

**Comment by maximebonhomme** [comment]
Thanks @Dhaiwat10 will open a new PR with updated source branch

**Pull request closed without merging**
