### PR TITLE
Fix/issue 379

### LINKED ISSUE #379: Dropdown Element
Currently we have a [DropdownMenu element](https://github.com/Developer-DAO/web3-ui/tree/main/packages/components/src/elements/DropdownMenu)

This should be renamed to Dropdown

A lot will be removed from this element to get to the goal of a single <Dropdown /> element

The element should act similar to this [tailwind dropdown component](https://tailwindui.com/components/application-ui/elements/dropdowns)

props will include:
- label?: string
- placeholder?: string
- items: string[]
- onSelect?: (val: any) => void

### PR DESCRIPTION
**Pull request by Nazeeh21**
Closes #379

## Description
This PR contains the following changes
- Renaming the `Dropdownmenu` component to `Dropdown` component
- Removed unused exports and imports of `radix` lib
- Added props
- Improve styling of the component

## 📝 Additional Information
I didn't have the clarity as to where to use the `placeholder` props, so for now, I've just used them in the place of `label` props. If that's not the required behavior, the pls lmk and I'll be happy to make the required changes. 

Also, suggestions are welcome regarding the styling if any.

### CODE REVIEW

**Comment by e-roy** [comment]
@Nazeeh21 hey friend, I've got this on my mind.  Just need to set up my environment locally to check before merge.  Sorry I've let this PR sit this long :)

**Comment by Nazeeh21** [comment]
hey @e-roy, no worries! take your time. :)

**Review by e-roy — APPROVED** [review]
thank you!

**Comment by e-roy** [comment]
fixing the CI / test-lint-build error in a upcoming PR

**Pull request merged**
