### PR TITLE
Fix: Export missing core components from root components

### LINKED ISSUE #326: it seems no export for NetworkSwitch component
https://github.com/Developer-DAO/web3-ui/blob/ef8df06dea5b36c4f5d65bf6e37288eaa9571146/packages/core/src/components/index.ts#L2

it seems no export for NetworkSwitch component, maybe this is a careless problem.

### PR DESCRIPTION
**Pull request by seromenho**
Closes #326 

## Description

Add missing exports on core/components/index.ts for the NetworkSwitch and TokenBalance components

### CODE REVIEW

**Comment by xdlrt** [comment]
hope this will be merged soon :)

**Comment by Dhaiwat10** [comment]
@allcontributors please @seromenho for code

**Comment by Dhaiwat10** [comment]
@allcontributors please add @seromenho for code

**Comment by seromenho** [comment]
@Dhaiwat10 Thank you

**Pull request merged**
