### PR TITLE
[hooks] Add `cacheProvider` prop to `<Provider />`

### LINKED ISSUE #310: Implement cached provider in Provider component
### Description

Currently connected state is not persisted, when I reload the page I have to connect to wallet again.

### Why is this needed?

I would like the feature to automatically connect to user wallet when user already connect it with the site once before already.

### Proposed Solution or API

when initiate web3modal we can pass cachedProvider flag

```
const web3Modal = new Web3Modal({
  ...
  cacheProvider: true,
});
```

when our page mounted we can check if there are cached provider

```
useEffect(() => {
  if (web3Modal.cachedProvider) {
    handleOnConnect();
  }
}, [])
```

### Additional Information

Example usage:
https://github.com/Web3Modal/web3modal/blob/master/example/src/App.tsx

### PR DESCRIPTION
**Pull request by jamescharlesworth**
See stories/useWriteContract for example.

Closes #310

## Description
This exposes cacheProvider as a prop to  `<Provider />` to allow persistence with Web3Modal.

## 📝 Additional Information

I'd like to implement some tests for this but wasn't sure how to mock accounts and didn't see any setup for that. Any ideas or examples on the best pattern to do that?

### CODE REVIEW

**Comment by RoseRompkxm** [comment]
This is exactly what this project is needed, why still no progress it's nearly 2 weeks!

**Comment by Dhaiwat10** [comment]
LGTM, thanks @jamescharlesworth!

**Comment by Dhaiwat10** [comment]
> I'd like to implement some tests for this but wasn't sure how to mock accounts and didn't see any setup for that. Any ideas or examples on the best pattern to do that?

I'm not really sure tbh. Maybe look into some existing tests that we have? I've seen some people use `ethereum-waffle` to mock stuff as well (that name might be slightly wrong)

**Comment by Dhaiwat10** [comment]
@allcontributors please add @jamescharlesworth for code

**Pull request merged**
