### PR TITLE
refactor: 💡 New Examples Folder

### LINKED ISSUE #242: Add ViteJS Example
**Context:**

After trying to setup `web3-ui` locally with [vitejs](https://vitejs.dev), I ran into blockers that preventing using the library.

**Proposal:**

Organize the examples folder to separate the different react platforms you can use to serve react with.

**_NOTE:_** This would be a first pass of supporting just vitejs as an example and then adding more and more in different issues/pull requests.

_Example:_ Proposed folder structure.

```diff
- example
+ examples
+  - nextjs
+  - vitejs
+  - cra
+  - gatsby
```

**Goal:**

Give more examples of how to use `web3-ui` with different libraries and frameworks.

### PR DESCRIPTION
**Pull request by codingwithmanny**
Includes multiple library/framework examples with nextjs and vitejs
being the first

BREAKING CHANGE: 🧨 n

✅ Closes: #242

Closes #242 

## Description

See [https://github.com/Developer-DAO/web3-ui/issues/242](https://github.com/Developer-DAO/web3-ui/issues/242)

### CODE REVIEW

**Comment by codingwithmanny** [comment]
@Dhaiwat10 @with-heart would you be able to review this?

**Comment by Dhaiwat10** [comment]
@codingwithmanny I will absolutely review this once I have internet that's NOT 500kbps lol. Hopefully soon

**Review by Dhaiwat10 — APPROVED** [review]

**Review by with-heart — APPROVED** [review]
LOVE IT! Also loved seeing this being worked on last Saturday in D_D. Didn't have a chance to attend but seemed like there were quite a few people in there at points!

**Comment by Dhaiwat10** [comment]
@allcontributors please add @codingwithmanny for code!

**Pull request merged**
