### PR TITLE
avatar-component

### PR DESCRIPTION
**Pull request by jwarshack**
Closes #110 

## Description

> Add a brief description
Created a component for ENS avatars using @react/davatar library.

## 📝 Additional Information

Component takes in an address and displays ENS avatar if applicable. If not, displays a jazzicon. Size is customizable but default value is 50px.

Screen Shot 2021-12-13 at 9 16 02 AM

### CODE REVIEW

**Comment by AlexNi245** [comment]
Hi @jwarshack thank you for adding this pr. It looks pretty good so far 2 thinks that I've found:

- Delete the package-lock.json since we are using yarn instead of npm
- add a changelog entry by running yarn changeset

**Comment by Dhaiwat10** [comment]
@jwarshack instead of using an image as a placeholder, why don't we use [blockies](https://www.npmjs.com/package/react-blockies)? That'd be cool

**Comment by jwarshack** [comment]
@Dhaiwat10 @AlexNi245 thanks guys.  Still figuring all this out but will resubmit a pr today

**Comment by Dhaiwat10** [comment]
@jwarshack any idea why the build is failing? You haven't made any changes to the `useWallet` source code yet it's throwing an error in that file. 🤔

**Comment by Dhaiwat10** [comment]
We're getting the same error in #97 too: https://github.com/Developer-DAO/web3-ui/runs/4580238077?check_suite_focus=true

Interesting

**Comment by with-heart** [comment]
@Dhaiwat10 you should open an issue documenting that problem!

**Comment by jwarshack** [comment]
@Dhaiwat10 @with-heart sorry been traveling for the last couple days and haven't had time to check in. Any update on this? I can look into it now

**Comment by Dhaiwat10** [comment]
@jwarshack I couldn't checkout your branch from Github desktop for some reason so I created a new PR off of your work here: #157. 

I rebased the branch against the main branch and resolved conflicts. The build passed locally. Let's see if it works.

**Comment by Dhaiwat10** [comment]
The build error seems to be gone but there's a Chromatic error. Chromatic is not opening up right now for some reason so I guess we'll have to wait until we can see what the error is.

**Comment by Dhaiwat10** [comment]
I'm closing this PR in favor of #157!

**Pull request closed without merging**
